import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'about/index',
    'about/who-we-serve',
    'about/humanity-first-flywheel',
    'get-jarvised',
    'get-your-company-jarvised',
    'partner',
    {
      type: 'category',
      label: 'Workshops',
      link: {
        type: 'doc',
        id: 'workshops/index',
      },
      items: [
        'workshops/supersuit-up',
        'workshops/readiness-quiz',
        'playbooks/practitioner/workshop-instructor-playbook',
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      link: {
        type: 'doc',
        id: 'tools/index',
      },
      items: [
        'tools/homebrew',
        'tools/git',
        'tools/github-cli',
        'tools/nodejs',
        'tools/vscode',
        'tools/remote-control',
        'tools/capturing-conversations',
        {
          type: 'category',
          label: 'Tool Setups',
          link: {
            type: 'doc',
            id: 'tools/tool-setups/index',
          },
          items: [
            'tools/tool-setups/claude-code-setup',
            'tools/tool-setups/codex-setup',
            'tools/tool-setups/hermes-setup',
            'tools/tool-setups/first-git-setup',
            'tools/tool-setups/workspace-setup',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Applied AI Practice',
      link: {
        type: 'doc',
        id: 'applied-ai-practice/index',
      },
      items: [
        'applied-ai-practice/earthshot',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      link: {
        type: 'doc',
        id: 'use-cases/index',
      },
      items: [
        'use-cases/getting-your-time-back',
        'use-cases/dealmaking',
        'use-cases/legacy',
        'use-cases/use-ai-to-hunt-for-the-right-solution',
      ],
    },
    {
      type: 'category',
      label: 'Philosophy',
      link: {
        type: 'doc',
        id: 'philosophy/index',
      },
      items: [
        'philosophy/canon',
        'philosophy/principles',
        'philosophy/north-star',
        'philosophy/voices-from-the-frontier',
        'philosophy/why-field-notes',
        'philosophy/why-making-money-matters',
        'philosophy/be-selfish-first',
        'philosophy/co-teaching-is-the-new-self-teaching',
        'philosophy/the-amplification-effect',
        'philosophy/your-two-futures',
        'philosophy/working-smart',
        'philosophy/rip-to-the-career-ladder',
        'philosophy/build-your-jarvis-in-community',
        'philosophy/jarvis-the-world-or-ai-is-doomed',
      ],
    },
    {
      type: 'category',
      label: 'Roles',
      link: {
        type: 'doc',
        id: 'roles/index',
      },
      items: [
        'roles/applied-ai-consultant',
        'roles/chief-ai-officer',
        'roles/business-os-administrator',
        'roles/agentic-os-trainer',
        'roles/community-leader',
        'roles/ai-enablement-architect',
        'roles/corporate-upskiller',
        'roles/applied-ai-streamliner',
        'roles/ai-advisor-to-the-ceo',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: {
        type: 'doc',
        id: 'concepts/index',
      },
      items: [
        'concepts/personal-agentic-os/index',
        {
          type: 'category',
          label: 'Sovereign Agentic Business OS',
          link: {
            type: 'doc',
            id: 'concepts/sovereign-agentic-business-os/index',
          },
          items: [
            'concepts/sovereign-agentic-business-os/principles',
            'concepts/sovereign-agentic-business-os/question-bank',
          ],
        },
        {
          type: 'category',
          label: 'Legacy',
          link: {
            type: 'doc',
            id: 'concepts/legacy/index',
          },
          items: [
            'concepts/legacy/why-it-matters',
            'concepts/legacy/getting-started',
            {
              type: 'category',
              label: 'Principles',
              items: [
                'concepts/legacy/dont-assume-common-sense',
                'concepts/legacy/align-before-committing',
                'concepts/legacy/make-every-file-count',
                'concepts/legacy/make-your-company-refactorable',
                'concepts/legacy/empower-your-knowledge-worker',
                'concepts/legacy/protect-your-truth',
              ],
            },
            {
              type: 'category',
              label: 'Processes',
              items: [
                'concepts/legacy/start-your-company-handbook',
                'concepts/legacy/migrate-to-refactorable-systems',
                'concepts/legacy/truth-as-context',
                'concepts/legacy/maintain-coherence',
                'concepts/legacy/refactor-your-information-architecture',
              ],
            },
            {
              type: 'category',
              label: 'Tools',
              items: [
                'concepts/legacy/source-controller',
                'concepts/legacy/voice-transcriber',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Harness Engineering',
          link: {
            type: 'doc',
            id: 'concepts/harness-engineering',
          },
          items: [
            'concepts/agentic-harness',
            'concepts/agentic-harnesses-for-everyone',
            'concepts/anatomy-of-a-harness',
            'concepts/the-case-for-simple-harnesses',
            'concepts/fat-skills',
            'concepts/learn-the-harness-not-the-wrapper',
            'concepts/understanding-why-the-gui-is-becoming-legacy',
          ],
        },
        'concepts/applied-ai',
        'concepts/applied-ai-practice',
        'concepts/applied-ai-practitioner',
        'concepts/sustained-commercial-success',
        'concepts/human-skills',
        'concepts/human-comparative-advantage',
        'concepts/imagination-economy',
        'concepts/latent-leverage',
        'concepts/angels-in-the-attributes',
        'concepts/strategy-is-the-new-execution',
        'concepts/agentic-exploration',
        'concepts/the-prolific-mode',
        'concepts/context-engineering',
        'concepts/context-searching',
        'concepts/intent-engineering',
        'concepts/prm',
        'concepts/agentic-relationship-management',
        'concepts/minimum-commercial-viability',
        'concepts/game-design',
        'concepts/spec-writing',
        'concepts/agi-whisperer',
        'concepts/vibe-curation',
        'concepts/liberation-architecture',
        'concepts/the-encounter',
        'concepts/activation',
        'concepts/build-what-big-ai-wont',
        'concepts/the-token-economy',
        'concepts/roles-to-workflows',
        'concepts/observable-behavior-engineering',
        'concepts/ignorance-debt',
        'concepts/the-tinkerers-curse',
        'concepts/the-permission-surface',
        'concepts/instruction-files',
        'concepts/orientation-budget',
        'concepts/dont-put-the-app-on-a-pedestal',
        'concepts/skill-file-first-app-second',
        'concepts/interview-prompts',
        'concepts/superprompt',
        'concepts/self-improving-enterprise',
        'concepts/agent-accessible-products',
        'concepts/computer-use',
        'concepts/forkable-is-the-new-sticky',
        'concepts/llms-txt',
        'concepts/self-improving-systems',
        'concepts/flow-state-infra',
        'concepts/the-chat-is-not-the-product',
        'concepts/the-chatbot-trap',
        'concepts/signalmaxxing',
        'concepts/always-on-agents',
        'concepts/train-your-agent',
        'concepts/context-overflow',
        'concepts/permissionless-knowledge',
        'concepts/compounding-docs',
        'concepts/the-life-harness',
        'concepts/mission-harness',
        'concepts/capture-process-compound',
        'concepts/the-omni-crisis',
        'concepts/the-water-line',
        'concepts/the-elevator-economy',
        'concepts/the-survivor-economy',
        'concepts/there-is-no-demand-for-average',
        'concepts/lossy-ai-telephone',
        'concepts/hypercontext-protocol',
        'concepts/context-lake',
        'concepts/minimum-viable-infrastructure',
        'concepts/the-lock-in-is-coming',
        'concepts/progressive-sovereignty',
        'concepts/literacies-that-matter',
        'concepts/scam-literacy',
        'concepts/the-unlock-question',
        'concepts/jarvis-workspace',
        'concepts/agentic-ux-rules',
        'concepts/being-someones-go-to-person',
        'concepts/applied-politics',
        'concepts/externalize-your-brain',
        'concepts/the-exocortex',
        'concepts/creative-congestion',
        'concepts/clips',
        'concepts/slopacalypse',
        'concepts/compound-drift',
        'concepts/slop-factory',
        'concepts/human-slop-factory',
        'concepts/llm-psychosis',
        'concepts/inclusive-technological-advancement',
        'concepts/regenerative-ai-advancement',
        'concepts/flaming-red-elephant',
        'concepts/command-centers',
        'concepts/hyperagency',
        'concepts/the-hyperagency-gap',
        'concepts/conjoined-agency',
        'concepts/jevons-paradox',
        'concepts/the-self-improving-human',
        'concepts/effective-agi',
        'concepts/four-levels-of-applied-ai-for-existing-businesses',
        'concepts/the-judgment-line',
        'concepts/the-sorting-hat',
        'concepts/robot-mode',
        'concepts/train-your-replacement-work',
        'concepts/human-emulators',
        'concepts/crutching',
        'concepts/raise-the-floor',
        'concepts/the-socratic-trainer',
        'concepts/corporate-upskilling',
        'concepts/the-tool-is-only-as-powerful-as-the-beholder',
        'concepts/see-your-own-thinking',
        'concepts/you-are-the-bottleneck',
        'concepts/the-overconfidence-trap',
        'concepts/the-tradeoff-era',
        'concepts/judgment-burnout',
        'concepts/imagination-economy-infrastructure',
        'concepts/personal-software',
        'concepts/agentic-strategy',
        'concepts/operational-reality',
        'concepts/ontology-as-substrate',
        'concepts/ontology-driven-development',
        'concepts/agentic-os-debt',
        'concepts/pirates-architects-and-archetypes-of-the-future',
        'concepts/community-of-practice',
        'concepts/anchor-of-a-scene',
      ],
    },
    {
      type: 'category',
      label: 'Case Studies',
      link: {
        type: 'doc',
        id: 'case-studies/index',
      },
      items: [
        'case-studies/rostam-mahabadi',
        'case-studies/ramp-glass',
      ],
    },
    {
      type: 'category',
      label: 'Playbooks',
      link: {
        type: 'doc',
        id: 'playbooks/index',
      },
      items: [
        {
          type: 'category',
          label: 'Chapter Leader',
          link: {
            type: 'doc',
            id: 'playbooks/chapter-leader/index',
          },
          items: [
            'playbooks/chapter-leader/starting-a-chapter',
            'playbooks/chapter-leader/launching-on-campus',
            'playbooks/chapter-leader/event-formats',
            'playbooks/chapter-leader/organizing-an-applied-ai-business-community',
            'playbooks/chapter-leader/applied-ai-live',
            'playbooks/chapter-leader/running-a-hackathon',
            'playbooks/chapter-leader/finding-a-photographer',
            'playbooks/chapter-leader/finding-a-venue',
            'playbooks/chapter-leader/generating-flyers',
            'playbooks/chapter-leader/recording-an-event',
            'playbooks/chapter-leader/case-study-interviews',
            'playbooks/chapter-leader/speaker-outreach',
            'playbooks/chapter-leader/event-promotion',
            'playbooks/chapter-leader/content-distribution',
            'playbooks/chapter-leader/building-partnerships',
            'playbooks/chapter-leader/hosting-an-event',
            'playbooks/chapter-leader/live-architecture-session',
            'playbooks/chapter-leader/writing-event-descriptions',
            'playbooks/chapter-leader/writing-and-sharing-event-recaps',
            'playbooks/chapter-leader/crm-setup',
            'playbooks/chapter-leader/linkedin-automation',
            'playbooks/chapter-leader/twitter-automation',
            'playbooks/chapter-leader/getting-things-done',
            'playbooks/chapter-leader/tools',
            {
              type: 'category',
              label: 'Event Recaps',
              link: { type: 'doc', id: 'playbooks/chapter-leader/event-recaps/index' },
              items: ['playbooks/chapter-leader/event-recaps/applied-ai-live-1', 'playbooks/chapter-leader/event-recaps/applied-ai-live-2'],
            },
          ],
        },
        {
          type: 'category',
          label: 'Presenter',
          link: {
            type: 'doc',
            id: 'playbooks/presenter/index',
          },
          items: [
            'playbooks/presenter/presenting-at-applied-ai-live',
          ],
        },
        {
          type: 'category',
          label: 'Practitioner',
          link: {
            type: 'doc',
            id: 'playbooks/practitioner/index',
          },
          items: [
            'playbooks/practitioner/post-workshop-cheat-sheet',
            'playbooks/practitioner/how-to-ask-help',
            'playbooks/practitioner/applied-ai-economy',
            'playbooks/practitioner/icp-clarity',
            'playbooks/practitioner/experimental-improvement',
            'playbooks/practitioner/pricing',
            'playbooks/practitioner/finding-clients',
            'playbooks/practitioner/pilot-pitch',
            'playbooks/practitioner/export-your-ai-history',
            'playbooks/practitioner/how-to-prompt-your-jarvis',
            'playbooks/practitioner/priming-your-jarvis',
            'playbooks/practitioner/restart-your-jarvis',
            'playbooks/practitioner/using-the-docs-with-your-jarvis',
            'playbooks/practitioner/start-your-wiki',
            {
              type: 'category',
              label: 'PRM',
              link: {
                type: 'doc',
                id: 'playbooks/practitioner/prm/index',
              },
              items: [
                'playbooks/practitioner/prm/auto-syncing-granola-notes',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Student / Explorer',
          link: {
            type: 'doc',
            id: 'playbooks/student/index',
          },
          items: [
            'playbooks/student/five-levels-of-value',
            'playbooks/student/you-are-what-you-eat',
          ],
        },
        {
          type: 'category',
          label: 'Business Owner',
          link: {
            type: 'doc',
            id: 'playbooks/business-owner/index',
          },
          items: [
            'playbooks/business-owner/why-ai',
            'playbooks/business-owner/quick-check',
            'playbooks/business-owner/situation-map',
            'playbooks/business-owner/pilot-scope',
            'playbooks/business-owner/beyond-automation',
            'playbooks/business-owner/hiring-practitioners',
            'playbooks/business-owner/dont-delegate-your-ai-literacy',
            'playbooks/business-owner/workflow-decomposition',
            'playbooks/business-owner/ai-readiness-by-function',
            'playbooks/business-owner/dont-scale-slop',
            'playbooks/business-owner/building-your-app',
            'playbooks/business-owner/ai-native-by-configuration',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Standards',
      link: { type: 'doc', id: 'standards/index' },
      items: [
        {
          type: 'category',
          label: 'INTEGRATE.md',
          link: { type: 'doc', id: 'standards/integrate-md/index' },
          items: [
            'standards/integrate-md/writing-guide',
            'standards/integrate-md/example',
          ],
        },
        {
          type: 'category',
          label: 'ALIGN.md',
          link: { type: 'doc', id: 'standards/align-md/index' },
          items: [
            'standards/align-md/writing-guide',
            'standards/align-md/example',
            'standards/align-md/template',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Specs',
      link: { type: 'doc', id: 'specs/index' },
      items: [
        'specs/practitioner-matching',
      ],
    },
    {
      type: 'category',
      label: 'Brand',
      link: {
        type: 'doc',
        id: 'brand/index',
      },
      items: [
        'brand/ai-generation',
      ],
    },
    {
      type: 'category',
      label: 'Get Activated / Subscribe',
      link: { type: 'doc', id: 'activate' },
      items: [
        'about/co-stewardship',
        'university-partnerships',
      ],
    },
    'code-of-conduct',
    'about/license',
  ],
};

export default sidebars;

